apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kuard
    name: kuard
    internalVersion: 0.0.1
  name: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    imagePullPolicy: IfNotPresent
    name: kuard
    resources:
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "512Mi"
        cpu: "1"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
