apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
  - name: mysql-client
    image: nginx
    volumeMounts:
    - name: connection
      mountPath: "/etc/connection"
      readOnly: true
  volumes:
  - name: connection
    secret:
      secretName: mysqlconnection